require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe GraceAssociatesController do

  # This should return the minimal set of attributes required to create a valid
  # GraceAssociate. As you add validations to GraceAssociate, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # GraceAssociatesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all grace_associates as @grace_associates" do
      grace_associate = GraceAssociate.create! valid_attributes
      get :index, {}, valid_session
      assigns(:grace_associates).should eq([grace_associate])
    end
  end

  describe "GET show" do
    it "assigns the requested grace_associate as @grace_associate" do
      grace_associate = GraceAssociate.create! valid_attributes
      get :show, {:id => grace_associate.to_param}, valid_session
      assigns(:grace_associate).should eq(grace_associate)
    end
  end

  describe "GET new" do
    it "assigns a new grace_associate as @grace_associate" do
      get :new, {}, valid_session
      assigns(:grace_associate).should be_a_new(GraceAssociate)
    end
  end

  describe "GET edit" do
    it "assigns the requested grace_associate as @grace_associate" do
      grace_associate = GraceAssociate.create! valid_attributes
      get :edit, {:id => grace_associate.to_param}, valid_session
      assigns(:grace_associate).should eq(grace_associate)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new GraceAssociate" do
        expect {
          post :create, {:grace_associate => valid_attributes}, valid_session
        }.to change(GraceAssociate, :count).by(1)
      end

      it "assigns a newly created grace_associate as @grace_associate" do
        post :create, {:grace_associate => valid_attributes}, valid_session
        assigns(:grace_associate).should be_a(GraceAssociate)
        assigns(:grace_associate).should be_persisted
      end

      it "redirects to the created grace_associate" do
        post :create, {:grace_associate => valid_attributes}, valid_session
        response.should redirect_to(GraceAssociate.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved grace_associate as @grace_associate" do
        # Trigger the behavior that occurs when invalid params are submitted
        GraceAssociate.any_instance.stub(:save).and_return(false)
        post :create, {:grace_associate => { "name" => "invalid value" }}, valid_session
        assigns(:grace_associate).should be_a_new(GraceAssociate)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        GraceAssociate.any_instance.stub(:save).and_return(false)
        post :create, {:grace_associate => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested grace_associate" do
        grace_associate = GraceAssociate.create! valid_attributes
        # Assuming there are no other grace_associates in the database, this
        # specifies that the GraceAssociate created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        GraceAssociate.any_instance.should_receive(:update_attributes).with({ "name" => "MyString" })
        put :update, {:id => grace_associate.to_param, :grace_associate => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested grace_associate as @grace_associate" do
        grace_associate = GraceAssociate.create! valid_attributes
        put :update, {:id => grace_associate.to_param, :grace_associate => valid_attributes}, valid_session
        assigns(:grace_associate).should eq(grace_associate)
      end

      it "redirects to the grace_associate" do
        grace_associate = GraceAssociate.create! valid_attributes
        put :update, {:id => grace_associate.to_param, :grace_associate => valid_attributes}, valid_session
        response.should redirect_to(grace_associate)
      end
    end

    describe "with invalid params" do
      it "assigns the grace_associate as @grace_associate" do
        grace_associate = GraceAssociate.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        GraceAssociate.any_instance.stub(:save).and_return(false)
        put :update, {:id => grace_associate.to_param, :grace_associate => { "name" => "invalid value" }}, valid_session
        assigns(:grace_associate).should eq(grace_associate)
      end

      it "re-renders the 'edit' template" do
        grace_associate = GraceAssociate.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        GraceAssociate.any_instance.stub(:save).and_return(false)
        put :update, {:id => grace_associate.to_param, :grace_associate => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested grace_associate" do
      grace_associate = GraceAssociate.create! valid_attributes
      expect {
        delete :destroy, {:id => grace_associate.to_param}, valid_session
      }.to change(GraceAssociate, :count).by(-1)
    end

    it "redirects to the grace_associates list" do
      grace_associate = GraceAssociate.create! valid_attributes
      delete :destroy, {:id => grace_associate.to_param}, valid_session
      response.should redirect_to(grace_associates_url)
    end
  end

end
